### ISSUE TITLE
Distribute Stinger library along with the Package

### ISSUE THREAD

**Issue by rohitvarkey** [rohitvarkey/StingerGraphs.jl#1]
Distribute a version of the shared library with the library. Or set it up using BinDeps.

**Comment by rohitvarkey** [comment]
Tips on how to do this available from Tony's [workshop](https://github.com/tkelman/JuliaCon2016workshop/blob/master/Workshop.ipynb)

**Comment by rohitvarkey** [comment]
Should get this done and integrated with travis for testing.

**Comment by jpfairbanks** [comment]
This is done with the /deps/build.jl file right?

**Comment by rohitvarkey** [comment]
Yep.
