### ISSUE TITLE
BFS Serial

### ISSUE THREAD

**Issue by rohitvarkey** [rohitvarkey/StingerGraphs.jl#7]
- [x] Bench
- [x] Tests

See - https://github.com/rohitvarkey/StingerWrapper.jl/pull/4

**Comment by jpfairbanks** [comment]
For tests: you can check that all edges implied by the parents array are in the graph using the `stinger_edge_weight` function.

**Comment by jpfairbanks** [comment]
The benchmarks were slow because of the max active vertices. You could just allocate enough for the maximum possible vertices.

**Comment by rohitvarkey** [comment]
Closed by #13.
